---
- name: Verify
  hosts: all
  become: true
  gather_facts: true
  vars:
    verify:
      config_file: "/opt/nginx/docker-compose.yml"
      config_line: "    image: nginx:latest"
      config_owner: "homelab"
      config_group: "homelab"
      config_mode: "0640"
      service_file: "/etc/systemd/system/compose-nginx.service"
      service_line: "Description=nginx service with docker compose"
      service_mode: "0644"
      daemon: "compose-nginx"
      port: 9999
      missiong_file: "/opt/nginx3/docker-compose.yml"

  tasks:
    - name: SmokeTests
      ansible.builtin.debug:
        msg:
          - "ansible_version => {{ ansible_version }}"
          - "ansible_distribution => {{ ansible_distribution }}"
          - "ansible_distribution_major_version => {{ ansible_distribution_major_version }}"
          - "ansible_os_family  => {{ ansible_os_family }}"
          - "ansible_system  => {{ ansible_system }}"

    - name: Check /opt/nginx/docker-compose.yml exist
      ansible.builtin.lineinfile:
        name: "{{ verify.config_file }}"
        line: "{{ verify.config_line }}"
        state: present
        owner: "homelab"
        group: "homelab"
        mode: "{{ verify.config_mode }}"
      check_mode: true
      register: molecule_config
      failed_when: (molecule_config is changed) or (molecule_config is failed)

    - name: Check /etc/systemd/system/compose-nginx.service exist
      ansible.builtin.lineinfile:
        name: "{{ verify.service_file }}"
        line: "{{ verify.service_line }}"
        state: present
        owner: "root"
        group: "root"
        mode: "{{ verify.service_mode }}"
      check_mode: true
      register: molecule_service
      failed_when: (molecule_service is changed) or (molecule_service is failed)

    - name: Check compose-nginx.service daemon
      ansible.builtin.service:
        name: "{{ verify.daemon }}"
        state: started
        enabled: true
      check_mode: true
      register: molecule_daemon
      failed_when: (molecule_daemon is changed) or (molecule_daemon is failed)
